class Penalty:

    def __init__(self, player):
        self.penalties = {
            "player": player,
            "No quitarse en ruck-ZG0": 0,
            "No quitarse en ruck-ZG1": 0,
            "No quitarse en ruck-ZG2": 0,
            "No quitarse en ruck-ZG3": 0,
            "Manos en el ruck-ZG0": 0,
            "Manos en el ruck-ZG1": 0,
            "Manos en el ruck-ZG2": 0,
            "Manos en el ruck-ZG3": 0,
            "Tirarse en el ruck-ZG0": 0,
            "Tirarse en el ruck-ZG1": 0,
            "Tirarse en el ruck-ZG2": 0,
            "Tirarse en el ruck-ZG2": 0,
            "Fuera de juego-ZG0": 0,
            "Fuera de juego-ZG1": 0,
            "Fuera de juego-ZG2": 0,
            "Fuera de juego-ZG3": 0,
            "Placaje alto-ZG0": 0,
            "Placaje alto-ZG1": 0,
            "Placaje alto-ZG2": 0,
            "Placaje alto-ZG3": 0,
            "Placaje peligroso-ZG0": 0,
            "Placaje peligroso-ZG1": 0,
            "Placaje peligroso-ZG2": 0,
            "Placaje peligroso-ZG3": 0,
            "Placaje sin brazos-ZG0": 0,
            "Placaje sin brazos-ZG1": 0,
            "Placaje sin brazos-ZG2": 0,
            "Placaje sin brazos-ZG3": 0,
            "Entrar por el lateral-ZG0": 0,
            "Entrar por el lateral-ZG1": 0,
            "Entrar por el lateral-ZG2": 0,
            "Entrar por el lateral-ZG3": 0,
            "Hundir el maul-ZG0": 0,
            "Hundir el maul-ZG1": 0,
            "Hundir el maul-ZG2": 0,
            "Hundir el maul-ZG3": 0,
            "Avant voluntario-ZG0": 0,
            "Avant voluntario-ZG1": 0,
            "Avant voluntario-ZG2": 0,
            "Avant voluntario-ZG3": 0,
            "Retenido-ZG0": 0,
            "Retenido-ZG1": 0,
            "Retenido-ZG2": 0,
            "Retenido-ZG2": 0,
            "Placaje retardado-ZG0": 0,
            "Placaje retardado-ZG1": 0,
            "Placaje retardado-ZG2": 0,
            "Placaje retardado-ZG3": 0,
            "Obstrucción-ZG0": 0,
            "Obstrucción-ZG1": 0,
            "Obstrucción-ZG2": 0,
            "Obstrucción-ZG3": 0,
            "Hundir la melé-ZG0": 0,
            "Hundir la melé-ZG1": 0,
            "Hundir la melé-ZG2": 0,
            "Hundir la melé-ZG3": 0,
            "Introducción parcial-ZG0": 0,
            "Introducción parcial-ZG1": 0,
            "Introducción parcial-ZG2": 0,
            "Introducción parcial-ZG3": 0,
            "Placaje en el aire-ZG0": 0,
            "Placaje en el aire-ZG1": 0,
            "Placaje en el aire-ZG2": 0,
            "Placaje en el aire-ZG3": 0,
        }

    def add_penalty(self, penalty_type: str, zone: str):
        self.penalties[f"{penalty_type}-{zone}"] += 1

    def get_penalties(self):
        return self.penalties
